language: php

php:
  - '7.3'

addons:
  sonarcloud:
    organization: "assoconnect"

cache:
    directories:
        - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction
  - composer require php-coveralls/php-coveralls
  - wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  
script:
  - vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml --log-junit ./tests/logs/phpunit.report.xml
  - php phpcs.phar --standard=PSR12 ./src ./tests
  - 'if [ ! -z "$SONAR_TOKEN" ]; then sonar-scanner; fi'
